---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: avalanche
  labels:
    app: avalanche
spec:
  replicas: 1
  selector:
    matchLabels:
      app: avalanche
  template:
    metadata:
      labels:
        app: avalanche
    spec:
      volumes:
      - name: avalanche
        persistentVolumeClaim:
          claimName: pvc-avalanche
      containers:
      - name: avalanche
        image: avalanchego:master
        command: ["/avalanchego/build/avalanchego"]
        args: ["--network-id=fuji"]
        ports:
        - name: http
          containerPort: 9650
        - containerPort: 9651
        livenessProbe:
          httpGet:
            path: /ext/health/liveness
            port: http 
          initialDelaySeconds: 30
          periodSeconds: 60
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /ext/health/readiness
            port: http 
          initialDelaySeconds: 60
          periodSeconds: 60
          failureThreshold: 5
        volumeMounts:
        - mountPath: "/root/.avalanchego"
          name: avalanche
