---
apiVersion: v1
kind: Service
metadata:
  name: avalanche
spec:
  type: LoadBalancer
  selector:
    app: avalanche
  ports:
    - name: http
      protocol: TCP
      port: 9650
      targetPort: http
    - name: tcp
      protocol: TCP
      port: 9651
      targetPort: 9651
