---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: avalanche
spec:
  storageClassName: avalanche
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 50Gi
  hostPath:
    path: /data/avalanche/
--- 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-avalanche
spec:
  storageClassName: avalanche
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
